<?php get_header(); ?>
<main id="top">
<section class="inner-hero inner-service"><div class="inner-hero-bg"><img src="<?php echo esc_url(lumiere_asset('event-01.jpg')); ?>" alt="Lumièreのステージ"></div><div class="inner-hero-copy"><p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">HOME</a> / SERVICE</p><p class="kicker">PERFORMANCE REQUEST</p><h1>光と熱狂を、<br>あなたの場所へ。</h1><p>企業イベント、地域のお祭り、学校行事、映像作品まで。</p></div><span class="inner-hero-number">05</span></section>
<section class="section services"><div class="section-label"><span>01</span> OUR SERVICE</div><div class="services-intro"><p class="kicker">DESIGN THE MOMENT</p><h2>その場所にしかない、<br><em>熱狂の設計。</em></h2><p>規模や目的に合わせて、演目・時間・出演人数・演出をご提案します。まずは企画内容をお聞かせください。</p></div><div class="service-grid">
<article class="service-card service-featured"><div class="service-image"><img src="<?php echo esc_url(lumiere_asset('event-01.jpg')); ?>" alt="ホノルルフェスティバル"></div><div class="service-content"><span class="service-number">01</span><p class="service-en">LIVE PERFORMANCE</p><h3>イベント出演</h3><p>地域のお祭り、企業イベント、学校行事、商業施設、式典まで。屋内・屋外を問わず、会場全体を巻き込む演出をつくります。</p><a href="<?php echo esc_url(home_url('/contact/')); ?>">出演を相談する <span>↗</span></a></div></article>
<article class="service-card"><span class="service-number">02</span><p class="service-en">FILM / MEDIA</p><h3>振付・メディア協力</h3><p>映画や映像作品のヲタ芸振付、出演、演技指導。企画段階から世界観に沿った動きを設計します。</p><a href="<?php echo esc_url(home_url('/contact/')); ?>">企画を相談する <span>↗</span></a></article>
<article class="service-card"><span class="service-number">03</span><p class="service-en">CORPORATE COLLAB</p><h3>企業コラボ</h3><p>商品・サービスのPR、社内イベント、スポンサー企画など、ご支援内容に合わせたコラボレーションをご提案します。</p><a href="<?php echo esc_url(home_url('/sponsor/')); ?>">スポンサー募集を見る <span>↗</span></a></article>
<article class="service-card"><span class="service-number">04</span><p class="service-en">SCHOOL / TEAM</p><h3>育成・チーム連携</h3><p>スクール、出張指導、所属チーム連携。文化を次世代へつなぐ活動も行っています。</p><a href="<?php echo esc_url(home_url('/school/')); ?>">スクールを見る <span>↗</span></a></article>
</div></section>
<section class="corporate-spec"><div><p class="kicker">PERFORMANCE GUIDE</p><h2>ご相談できること。</h2></div><dl><div><dt>対応会場</dt><dd>屋内・屋外 / ステージ規模は応相談</dd></div><div><dt>出演時間</dt><dd>イベント構成に合わせてご提案</dd></div><div><dt>出演人数</dt><dd>演目・スペース・ご予算に合わせて調整</dd></div><div><dt>音響・照明</dt><dd>会場設備を確認し、必要条件をご案内</dd></div><div><dt>ご相談の流れ</dt><dd>概要確認 → ご提案・お見積り → 内容確定 → 本番</dd></div></dl></section>
<section class="team-call"><div class="team-call-bg"><img src="<?php echo esc_url(lumiere_asset('event-05.jpg')); ?>" alt=""></div><div class="team-call-copy"><p class="kicker">FROM REQUEST TO STAGE</p><h2>まずは、企画の<br>輪郭だけでも。</h2><p>会場、目的、時期が決まりきっていない段階でも構いません。イベント出演、映像振付、学校公演など、実現方法を一緒に整理します。</p><a class="button button-primary" href="<?php echo esc_url(home_url('/contact/')); ?>">出演・仕事を相談する <span>↗</span></a></div><p class="team-call-en">LET'S CREATE</p></section>
<?php get_template_part('template-parts/contact-cta'); ?>
</main>
<?php get_footer(); ?>
