<?php get_header(); $videos=get_posts(array('post_type'=>'lumiere_video','posts_per_page'=>24,'orderby'=>'date','order'=>'DESC')); ?>
<main id="top">
<section class="inner-hero movie-hero"><div class="inner-hero-bg"><img src="<?php echo esc_url(lumiere_asset('event-06.jpg')); ?>" alt="Lumièreの動画ギャラリー"></div><div class="inner-hero-copy"><p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">HOME</a> / MOVIES</p><p class="kicker">MOVIE GALLERY</p><h1>光は、映像でも<br>熱を持つ。</h1><p>動画は管理画面から追加・差し替えできます。</p></div><span class="inner-hero-number">06</span></section>
<section class="section movie-gallery"><div class="section-label"><span>01</span> WATCH LUMIÈRE</div><div class="gallery-heading"><div><p class="kicker">SELECTED MOVIES</p><h2>音を感じる、<br><em>光を観る。</em></h2></div><a href="<?php echo esc_url(lumiere_mod('youtube_url','https://www.youtube.com/')); ?>" target="_blank" rel="noreferrer">YOUTUBE CHANNEL <span>↗</span></a></div><div class="movie-card-grid">
<?php if($videos): foreach($videos as $i=>$video): $url=get_post_meta($video->ID,'video_url',true); $event=get_post_meta($video->ID,'video_event',true); ?><a href="<?php echo esc_url($url ?: get_permalink($video)); ?>" target="_blank" rel="noreferrer"><div><?php if(has_post_thumbnail($video)) echo get_the_post_thumbnail($video,'large'); else echo '<img src="'.esc_url(lumiere_asset('event-0'.(($i%7)+1).'.jpg')).'" alt="">'; ?><span class="movie-play">▶</span></div><p><?php echo esc_html($event ?: 'MOVIE'); ?> / <?php echo esc_html(str_pad((string)($i+1),2,'0',STR_PAD_LEFT)); ?></p><h3><?php echo esc_html(get_the_title($video)); ?></h3><i>WATCH ↗</i></a><?php endforeach; else: $fallback=array(array('WWC 2026','ヲタ芸 / 黎明二咲ケ','event-01.jpg','https://www.youtube.com/watch?v=47wKIysCJ58'),array('COLLABORATION','自衛隊とのコラボヲタ芸','event-05.jpg',lumiere_mod('youtube_url','https://www.youtube.com/')),array('MEDIA','フィリピンのテレビ局で紹介','event-06.jpg',lumiere_mod('youtube_url','https://www.youtube.com/')),array('LIVE ARCHIVE','イベント出演アーカイブ','event-02.jpg',lumiere_mod('youtube_url','https://www.youtube.com/'))); foreach($fallback as $i=>$movie): ?><a href="<?php echo esc_url($movie[3]); ?>" target="_blank" rel="noreferrer"><div><img src="<?php echo esc_url(lumiere_asset($movie[2])); ?>" alt=""><span class="movie-play">▶</span></div><p><?php echo esc_html($movie[0]); ?> / <?php echo esc_html(str_pad((string)($i+1),2,'0',STR_PAD_LEFT)); ?></p><h3><?php echo esc_html($movie[1]); ?></h3><i>WATCH ↗</i></a><?php endforeach; endif; ?>
</div></section>
<?php get_template_part('template-parts/contact-cta'); ?>
</main>
<?php get_footer(); ?>
