<?php get_header(); ?>
<main id="top">
<section class="inner-hero organization-hero"><div class="inner-hero-bg"><img src="<?php echo esc_url(lumiere_asset('organization-hero-team.jpg')); ?>" alt="スタジオでくつろぐLumièreメンバー"></div><div class="inner-hero-copy"><p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">HOME</a> / ORGANIZATION</p><p class="kicker">OUR ECOSYSTEM</p><h1>一つのチームから、<br>文化の輪へ。</h1><p>活動、育成、企業連携。それぞれの窓口と役割を分かりやすく。</p></div><span class="inner-hero-number">01</span></section>
<section class="section organization-section"><div class="section-label"><span>01</span> STRUCTURE</div><div class="organization-heading"><p class="kicker">WHO DOES WHAT</p><h2>つくる。育てる。<br><em>社会とつなぐ。</em></h2><p>一般・ファン向けの活動と、法人・団体向けの窓口を整理し、必要な情報へ迷わず進めます。</p></div><div class="org-map"><div class="org-root"><span>ASSOCIATION</span><h3>一般社団法人<br>ヲタ芸普及協会</h3><p>文化普及・法人団体窓口・所属チーム連携</p></div><div class="org-branches" id="teams"><a href="<?php echo esc_url(home_url('/about/')); ?>"><span>PERFORMANCE</span><h3>Lumière</h3><p>出演・振付・メディア</p></a><a href="<?php echo esc_url(home_url('/junior/')); ?>"><span>NEXT GENERATION</span><h3>ルミエールJr.</h3><p>次世代チーム</p></a><a href="<?php echo esc_url(home_url('/school/')); ?>"><span>EDUCATION</span><h3>WLD SCHOOL</h3><p>対面・出張・オンライン</p></a><a href="https://fbeventprojectsolutions.com/" target="_blank" rel="noreferrer"><span>RELATED PROJECT</span><h3>WOOD BELL</h3><p>関連活動・制作サポート</p></a></div></div></section>
<section class="team-call" id="team"><div class="team-call-bg"><img src="<?php echo esc_url(lumiere_asset('event-05.jpg')); ?>" alt=""></div><div class="team-call-copy"><p class="kicker">CALLING ALL TEAMS</p><h2>その光を、<br>次のステージへ。</h2><p>一般社団法人ヲタ芸普及協会では、ともに文化を広げる所属チームを募集しています。活動地域や経験年数は問いません。</p><a class="button button-primary" href="<?php echo esc_url(home_url('/contact/')); ?>">所属について相談する <span>↗</span></a></div><p class="team-call-en">JOIN THE MOVEMENT</p></section>
<section class="org-contact-path"><div><span>FOR BUSINESS</span><h2>企業・自治体・<br>団体の方へ</h2><p>出演、振付、メディア、スポンサー、協会連携のご相談。</p><a href="<?php echo esc_url(home_url('/contact/')); ?>">法人窓口へ ↗</a></div><div><span>FOR EVERYONE</span><h2>一般・ファン・<br>参加希望の方へ</h2><p>スクール、ジュニア、チーム所属、活動についてのご相談。</p><a href="<?php echo esc_url(home_url('/contact/')); ?>">一般窓口へ ↗</a></div></section>
<?php get_template_part('template-parts/contact-cta'); ?>
</main>
<?php get_footer(); ?>
