<?php get_header(); $work_posts = get_posts(array('post_type'=>'lumiere_work','posts_per_page'=>24,'meta_key'=>'work_year','orderby'=>'meta_value_num date','order'=>'DESC')); ?>
<main id="top">
<section class="inner-hero inner-works"><div class="inner-hero-bg"><picture><source media="(max-width: 720px)" srcset="<?php echo esc_url(lumiere_asset('works-hero-duo-mobile.jpg')); ?>"><img src="<?php echo esc_url(lumiere_asset('works-hero-duo.jpg')); ?>" alt="Lumièreメンバーのオフショット"></picture></div><div class="inner-hero-copy"><p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">HOME</a> / WORKS</p><p class="kicker">ACHIEVEMENTS</p><h1>挑戦の数だけ、<br>光は強くなる。</h1><p>千葉の地域イベントから、ハワイのステージ、映画、メディアへ。</p></div><span class="inner-hero-number">04</span></section>
<?php if ($work_posts) : ?><section class="section cms-work-section"><div class="section-label"><span>01</span> LATEST WORKS</div><div class="cms-work-grid"><?php foreach ($work_posts as $work) : $year=get_post_meta($work->ID,'work_year',true); $category=get_post_meta($work->ID,'work_category',true); $video=get_post_meta($work->ID,'work_video_url',true); ?><article><?php if (has_post_thumbnail($work)) echo get_the_post_thumbnail($work,'large'); ?><span><?php echo esc_html($year); ?> / <?php echo esc_html($category); ?></span><h3><?php echo esc_html(get_the_title($work)); ?></h3><p><?php echo esc_html(wp_trim_words($work->post_content,28)); ?></p><a href="<?php echo esc_url($video ?: get_permalink($work)); ?>"<?php echo $video ? ' target="_blank" rel="noreferrer"' : ''; ?>>VIEW ↗</a></article><?php endforeach; ?></div></section><?php endif; ?>
<section class="works"><div class="works-sticky"><div class="section-label light"><span><?php echo $work_posts ? '02':'01'; ?></span> OUR JOURNEY</div><p class="kicker">2022 — 2026</p><h2>光がつないだ、<br><em>挑戦の軌跡。</em></h2><p>各年の「映像を見る」から、YouTubeで活動の様子をご覧いただけます。</p><a class="outline-button" href="<?php echo esc_url(lumiere_mod('youtube_url','https://www.youtube.com/')); ?>" target="_blank" rel="noreferrer">YOUTUBE CHANNEL <span>↗</span></a></div><div class="timeline">
<?php $periods=array(
array('2026','世界へ、そして次の頂点へ。',array('ホノルルフェスティバル2026 出演','第3回パフォーマーカップ 優勝','東京ドイツ村・千葉日報カルチャー祭','四街道わくわくフェス・北条ビーチマーケット','地域新聞社イベント・平井花火・高洲祭り'),'https://www.youtube.com/watch?v=47wKIysCJ58'),
array('2025','映画・メディアへ活動を拡張。',array('映画ヲタ芸振付・企業公演','さんばしまつり花火大会 大トリ前座','チバテレ・ラジオ出演','銀座・築地・イオンほか多数公演'),'https://www.youtube.com/results?search_query=%E3%83%AB%E3%83%9F%E3%82%A8%E3%83%BC%E3%83%AB+%E3%83%B2%E3%82%BF%E8%8A%B8+2025'),
array('2024','パフォーマーカップ 優勝。',array('JRイベント公演','四街道中央公園','市原市学校・船橋イオン','パフォーマーカップ優勝'),'https://www.youtube.com/results?search_query=%E3%83%AB%E3%83%9F%E3%82%A8%E3%83%BC%E3%83%AB+%E3%83%91%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%B3%E3%82%B9%E3%82%AB%E3%83%83%E3%83%97+2024'),
array('2023–22','一本の光から始まった。',array('房総フェスタ','市原市学校公演','いすみの晩・12名でヲタ芸披露'),'https://www.youtube.com/results?search_query=%E3%83%AB%E3%83%9F%E3%82%A8%E3%83%BC%E3%83%AB+%E3%83%B2%E3%82%BF%E8%8A%B8+%E5%8D%83%E8%91%89'));
foreach($periods as $i=>$period): ?><article class="timeline-item"><div class="timeline-year"><span><?php echo esc_html($period[0]); ?></span><i><?php echo esc_html(str_pad((string)($i+1),2,'0',STR_PAD_LEFT)); ?></i></div><h3><?php echo esc_html($period[1]); ?></h3><ul><?php foreach($period[2] as $item): ?><li><?php echo esc_html($item); ?></li><?php endforeach; ?></ul><a href="<?php echo esc_url($period[3]); ?>" target="_blank" rel="noreferrer"><span class="play">▶</span> 映像を見る</a></article><?php endforeach; ?>
</div></section>
<section class="movie-section"><div class="movie-frame"><iframe src="https://www.youtube-nocookie.com/embed/47wKIysCJ58?rel=0" title="Lumière プロモーション動画" allowfullscreen loading="lazy"></iframe></div><div class="movie-copy"><span>OFFICIAL MOVIE / 04:06</span><h2>言葉より先に、<br>光が語る。</h2><p>【WWC2026】ヲタ芸 / 黎明二咲ケ<br>Lumière × Wotagei World Cup</p></div></section>
<section class="section gallery-section"><div class="section-label"><span>03</span> 2026 HIGHLIGHTS</div><div class="gallery-heading"><div><p class="kicker">FROM HONOLULU</p><h2>世界で灯した、<br><em>新しい光。</em></h2></div><a href="<?php echo esc_url(lumiere_mod('instagram_url','https://www.instagram.com/lumiere20241103')); ?>" target="_blank" rel="noreferrer">INSTAGRAM <span>↗</span></a></div><div class="gallery-grid"><?php foreach(array(2,4,6,7) as $i=>$num): ?><figure class="gallery-<?php echo esc_attr((string)($i+1)); ?>"><img src="<?php echo esc_url(lumiere_asset('event-0'.$num.'.jpg')); ?>" alt="Lumièreの活動風景" loading="lazy"></figure><?php endforeach; ?></div></section>
<?php get_template_part('template-parts/contact-cta'); ?>
</main>
<?php get_footer(); ?>
