<?php get_header(); ?>
<main id="top">
<section class="inner-hero inner-about"><div class="inner-hero-bg"><img src="<?php echo esc_url(lumiere_asset('event-03.jpg')); ?>" alt="Lumière メンバー"></div><div class="inner-hero-copy"><p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">HOME</a> / LUMIÈRE</p><p class="kicker">LUMIÈRE OFFICIAL</p><h1>光の向こうに、<br>人がいる。</h1><p>協会公式パフォーマンスチームLumièreのプロフィール、想い、活動をご紹介します。</p></div><span class="inner-hero-number">10</span></section>
<section class="section about about-page"><div class="section-label"><span>01</span> OUR MISSION</div><div class="about-copy"><p class="kicker">BEYOND THE GLOW</p><h2>ヲタ芸を、<br><em>誇れる文化</em>へ。</h2><div class="about-body"><p>光る棒を振る。ただそれだけに見える動きの奥に、緻密な振付、鍛錬、そして仲間との呼吸があります。Lumièreは、ヲタ芸を誰もが心を動かされるステージ・エンターテインメントへ進化させるチームです。</p><p>地域イベント、企業公演、映画振付、スクールを通して、年齢や経験を越えて人がつながる場所をつくります。千葉から全国へ、そして世界へ。</p></div></div><div class="about-visuals"><figure class="photo photo-main"><img src="<?php echo esc_url(lumiere_asset('event-03.jpg')); ?>" alt="ホノルルフェスティバルに出演したLumière"></figure><figure class="photo photo-sub"><img src="<?php echo esc_url(lumiere_asset('member-kejan.jpg')); ?>" alt="Lumièreメンバー"></figure><p class="vertical-copy">TURN LIGHT INTO CULTURE</p></div></section>
<?php
$member_posts = get_posts(array('post_type' => 'lumiere_member', 'posts_per_page' => -1, 'orderby' => 'menu_order title', 'order' => 'ASC'));
$fallback_members = array(array('KEJAN','ケジャン','リーダー・振付','member-kejan.jpg'),array('SUBARU','スバル','サブリーダー・講師','member-subaru.jpg'),array('CHLOE','クロエ','映像編集・パフォーマー','member-chloe.jpg'),array('HIRO','ヒロ','サポートメンバー','member-hiro.jpg'),array('SEIREI','青零','サポートメンバー','member-seirei.jpg'));
?>
<section class="section members"><div class="section-label"><span>02</span> THE TEAM</div><div class="member-heading"><div><p class="kicker">MEET THE LIGHT</p><h2>ひとりの個性が、<br><em>ひとつの光</em>になる。</h2></div><p>振付、講師、映像編集。異なる強みを持つメンバーが、ひとつのステージをつくります。</p></div><div class="member-grid">
<?php if ($member_posts) : foreach ($member_posts as $i => $member) : $roman = get_post_meta($member->ID, 'member_roman', true); $role = get_post_meta($member->ID, 'member_role', true); ?><article class="member-card"><div class="member-image"><?php if (has_post_thumbnail($member)) echo get_the_post_thumbnail($member, 'large', array('loading' => 'lazy', 'alt' => 'Lumière ' . get_the_title($member))); else echo '<img src="' . esc_url(lumiere_asset('logo.jpg')) . '" alt="Lumière">'; ?></div><span><?php echo esc_html(str_pad((string)($i+1),2,'0',STR_PAD_LEFT)); ?></span><h3><?php echo esc_html($roman ?: get_the_title($member)); ?><small><?php echo esc_html(get_the_title($member)); ?></small></h3><p><?php echo esc_html($role); ?></p></article><?php endforeach; else : foreach ($fallback_members as $i => $member) : ?><article class="member-card"><div class="member-image"><img src="<?php echo esc_url(lumiere_asset($member[3])); ?>" alt="Lumière <?php echo esc_attr($member[1]); ?>" loading="lazy"></div><span><?php echo esc_html(str_pad((string)($i+1),2,'0',STR_PAD_LEFT)); ?></span><h3><?php echo esc_html($member[0]); ?><small><?php echo esc_html($member[1]); ?></small></h3><p><?php echo esc_html($member[2]); ?></p></article><?php endforeach; endif; ?>
</div></section>
<section class="values-section"><article><span>01</span><p>VALUE</p><h3>技術に、誠実である。</h3><small>一本の光、ひとつの動きまで妥協しない。</small></article><article><span>02</span><p>VALUE</p><h3>誰もが、輝ける。</h3><small>年齢や経験を越えて挑戦できる場所をつくる。</small></article><article><span>03</span><p>VALUE</p><h3>地域から、世界へ。</h3><small>足元のつながりを大切に、大きな舞台へ挑む。</small></article></section>
<section class="section message-section"><div class="section-label"><span>03</span> MESSAGE</div><div class="message-photo"><img src="<?php echo esc_url(lumiere_asset('director.png')); ?>" alt="代表 鈴木桃子" loading="lazy"></div><div class="message-copy"><p class="kicker">FROM THE DIRECTOR</p><h2>誰もが輝ける場所を、<br>光と音でつくりたい。</h2><p>私たちはヲタ芸という独自のパフォーマンスを通じて、光と音が融合する新しいエンターテインメントを発信しています。地域イベントから全国、そして世界へ。出演やメディア活動、スクール事業を通して、もっと多くの方にこの文化の魅力を知っていただけるよう挑戦を続けます。</p><div class="signature"><span>代表 / マネージャー</span><strong>鈴木 桃子</strong></div></div></section>
<?php get_template_part('template-parts/contact-cta'); ?>
</main>
<?php get_footer(); ?>
