<?php get_header(); ?>
<main id="top">
<section class="inner-hero inner-contact"><div class="inner-hero-bg"><img src="<?php echo esc_url(lumiere_asset('event-07.jpg')); ?>" alt="Lumièreの活動風景"></div><div class="inner-hero-copy"><p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">HOME</a> / CONTACT</p><p class="kicker">START A CONVERSATION</p><h1>まだ輪郭のない<br>アイデアから。</h1><p>出演、レッスン、所属、スポンサー。まずはお気軽にお話しください。</p></div><span class="inner-hero-number">09</span></section>
<section class="section contact-guide"><div class="section-label"><span>01</span> HOW TO CONTACT</div><div class="contact-guide-heading"><p class="kicker">CHOOSE A CHANNEL</p><h2>ご都合のよい方法で、<br><em>ご相談ください。</em></h2></div><div class="contact-guide-grid"><a href="<?php echo esc_url(lumiere_mod('line_url','https://lin.ee/F5EQxq5')); ?>" target="_blank" rel="noreferrer"><span>01 / LINE</span><h3>お急ぎのご相談</h3><p>出演日程やレッスンについて、LINE公式アカウントから気軽にご相談いただけます。</p><i>↗</i></a><a href="mailto:<?php echo esc_attr(antispambot(lumiere_mod('email','otagei.fukyuu@gmail.com'))); ?>"><span>02 / MAIL</span><h3>資料を添えたご相談</h3><p>企画書やイベント概要がある場合は、メールでお送りください。</p><i>↗</i></a><a href="tel:<?php echo esc_attr(lumiere_phone_href()); ?>"><span>03 / TEL</span><h3>お電話でのご相談</h3><p>受付時間 9:00–22:00。出演中などで応答できない場合は折り返します。</p><i>↗</i></a></div></section>
<section class="contact-form-section"><div class="contact-form-copy"><p class="kicker">CONTACT FORM</p><h2>目的に合わせて、<br>お聞かせください。</h2><p>通常2営業日以内を目安にご返信します。</p></div><div class="contact-form-wrap">
<?php if (isset($_GET['sent'])) : ?><p class="form-notice success">お問い合わせを送信しました。ありがとうございます。</p><?php elseif (isset($_GET['error'])) : ?><p class="form-notice error">送信できませんでした。入力内容をご確認ください。</p><?php endif; ?>
<form action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><input type="hidden" name="action" value="lumiere_contact"><?php wp_nonce_field('lumiere_contact','lumiere_contact_nonce'); ?><label class="form-honeypot">会社Webサイト<input type="text" name="company_website" tabindex="-1" autocomplete="off"></label><label><span>お問い合わせ目的</span><select name="contact_type" required><option value="">選択してください</option><option>出演依頼</option><option>企業・自治体案件</option><option>スクール</option><option>ジュニアチーム</option><option>所属チーム</option><option>スポンサー</option><option>コラボ相談</option><option>メディア取材</option><option>グッズ</option><option>その他</option></select></label><label><span>お名前 / ご担当者名</span><input type="text" name="contact_name" required></label><label><span>メールアドレス</span><input type="email" name="contact_email" required></label><label><span>ご相談内容</span><textarea name="contact_message" rows="8" required></textarea></label><button type="submit">内容を送信する <i>↗</i></button></form>
</div></section>
<section class="section faq-section"><div class="section-label"><span>02</span> FAQ</div><div class="faq-heading"><p class="kicker">QUESTIONS</p><h2>よくあるご質問。</h2></div><div class="faq-list"><details><summary><span>Q</span>どのようなイベントに出演できますか？<i>＋</i></summary><p>地域のお祭り、企業イベント、学校行事、商業施設、式典など幅広く対応します。</p></details><details><summary><span>Q</span>スクールは未経験でも参加できますか？<i>＋</i></summary><p>もちろんです。サイリウムの持ち方や基本動作から丁寧にお伝えします。</p></details><details><summary><span>Q</span>スポンサーの支援内容は相談できますか？<i>＋</i></summary><p>ご予算や目的に合わせて、出演、コラボレーション、SNSでの発信など柔軟にご相談いただけます。</p></details><details><summary><span>Q</span>所属チームになるための条件はありますか？<i>＋</i></summary><p>活動地域や年数だけで判断しません。活動内容やこれから挑戦したいことを伺います。</p></details></div></section>
</main>
<?php get_footer(); ?>
